<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `www_kaifamei_com_ecms_infoclass_app`;");
E_C("CREATE TABLE `www_kaifamei_com_ecms_infoclass_app` (
  `classid` int(10) unsigned NOT NULL DEFAULT '0',
  `zz_title` text NOT NULL,
  `z_title` varchar(255) NOT NULL DEFAULT '',
  `qz_title` varchar(255) NOT NULL DEFAULT '',
  `save_title` varchar(10) NOT NULL DEFAULT '',
  `zz_titlepic` text NOT NULL,
  `z_titlepic` varchar(255) NOT NULL DEFAULT '',
  `qz_titlepic` varchar(255) NOT NULL DEFAULT '',
  `save_titlepic` varchar(10) NOT NULL DEFAULT '',
  `zz_newstime` text NOT NULL,
  `z_newstime` varchar(255) NOT NULL DEFAULT '',
  `qz_newstime` varchar(255) NOT NULL DEFAULT '',
  `save_newstime` varchar(10) NOT NULL DEFAULT '',
  `zz_ftitle` text NOT NULL,
  `z_ftitle` varchar(255) NOT NULL DEFAULT '',
  `qz_ftitle` varchar(255) NOT NULL DEFAULT '',
  `save_ftitle` varchar(10) NOT NULL DEFAULT '',
  `zz_smalltext` text NOT NULL,
  `z_smalltext` varchar(255) NOT NULL DEFAULT '',
  `qz_smalltext` varchar(255) NOT NULL DEFAULT '',
  `save_smalltext` varchar(10) NOT NULL DEFAULT '',
  `zz_writer` text NOT NULL,
  `z_writer` varchar(255) NOT NULL DEFAULT '',
  `qz_writer` varchar(255) NOT NULL DEFAULT '',
  `save_writer` varchar(10) NOT NULL DEFAULT '',
  `zz_befrom` text NOT NULL,
  `z_befrom` varchar(255) NOT NULL DEFAULT '',
  `qz_befrom` varchar(255) NOT NULL DEFAULT '',
  `save_befrom` varchar(10) NOT NULL DEFAULT '',
  `zz_newstext` text NOT NULL,
  `z_newstext` varchar(255) NOT NULL DEFAULT '',
  `qz_newstext` varchar(255) NOT NULL DEFAULT '',
  `save_newstext` varchar(10) NOT NULL DEFAULT '',
  `zz_diggtop` text NOT NULL,
  `z_diggtop` varchar(255) NOT NULL DEFAULT '',
  `qz_diggtop` varchar(255) NOT NULL DEFAULT '',
  `save_diggtop` varchar(10) NOT NULL DEFAULT '',
  `zz_type` text NOT NULL,
  `z_type` varchar(255) NOT NULL,
  `qz_type` varchar(255) NOT NULL,
  `save_type` varchar(10) NOT NULL,
  `zz_typei` text NOT NULL,
  `z_typei` varchar(255) NOT NULL,
  `qz_typei` varchar(255) NOT NULL,
  `save_typei` varchar(10) NOT NULL,
  `zz_size` text NOT NULL,
  `z_size` varchar(255) NOT NULL,
  `qz_size` varchar(255) NOT NULL,
  `save_size` varchar(10) NOT NULL,
  `zz_morepic` text NOT NULL,
  `z_morepic` varchar(255) NOT NULL,
  `qz_morepic` varchar(255) NOT NULL,
  `save_morepic` varchar(10) NOT NULL,
  `zz_bb` text NOT NULL,
  `z_bb` varchar(255) NOT NULL,
  `qz_bb` varchar(255) NOT NULL,
  `save_bb` varchar(10) NOT NULL,
  `zz_xtyq` text NOT NULL,
  `z_xtyq` varchar(255) NOT NULL,
  `qz_xtyq` varchar(255) NOT NULL,
  `save_xtyq` varchar(10) NOT NULL,
  `zz_yy` text NOT NULL,
  `z_yy` varchar(255) NOT NULL,
  `qz_yy` varchar(255) NOT NULL,
  `save_yy` varchar(10) NOT NULL,
  `zz_kfs` text NOT NULL,
  `z_kfs` varchar(255) NOT NULL,
  `qz_kfs` varchar(255) NOT NULL,
  `save_kfs` varchar(10) NOT NULL,
  `zz_downurl` text NOT NULL,
  `z_downurl` varchar(255) NOT NULL,
  `qz_downurl` varchar(255) NOT NULL,
  `save_downurl` varchar(10) NOT NULL,
  `zz_yjh` text NOT NULL,
  `z_yjh` varchar(255) NOT NULL,
  `qz_yjh` varchar(255) NOT NULL,
  `save_yjh` varchar(10) NOT NULL,
  `zz_qx` text NOT NULL,
  `z_qx` varchar(255) NOT NULL,
  `qz_qx` varchar(255) NOT NULL,
  `save_qx` varchar(10) NOT NULL,
  PRIMARY KEY (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");

@include("../../inc/footer.php");
?>